### ISSUE TITLE
Nitrous/learn

### ISSUE THREAD

**Issue by avanover0311** [learn-co-curriculum/ttt-9-play-loop#18]
My learn and nitrous are not communicating right.  Nitrous tells me my lesson is correct and complete and I have submitted it, but learn is not showing it updated and I really moved forward till it does.

**Comment by AnnJohn** [comment]
Hi @avanover0311 sorry about this. Since this is a technical problem, could you please file a bug report? If you hover over your profile pic in Learn, you'll see an option to report a bug. 

You can also use the Ask a Question button in Learn as well.
