### ISSUE TITLE
Mysterious code appeared after logging back in

### ISSUE THREAD

**Issue by alyssa0528** [learn-co-curriculum/ttt-9-play-loop#26]
Hi,

I had passed this lesson, but when I went back into it to look at my play method, I saw this in my play.rb file:

# Define your play method below
def play(board)
  counter = 0
<<<<<<< HEAD
  until counter == 9
    turn(board)
    counter += 1 
  end
=======
  loop do
    counter += 1 
    turn(board)
    if counter > 9 
      break 
    end
  end 
>>>>>>> 4806c45223ccb7dbd5b2390d4bfd890fb1ce5b29
end

I had never seen anything like this before, and I wasn't sure if it was an issue with the IDE or Learn software, so I wanted to ask. Thanks!

**Comment by curiositypaths** [comment]
Hi there,

Looks like you received a Git merge conflict. You can read about Git merge conflicts [here](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/).

As always thank you for contributing!
